### PR TITLE
fix: Default applicarion scenario configuration is not running

### LINKED ISSUE #39: Default applicarion scenario configuration is not running
In the Current release version: https://github.com/AI4WORK-Project/sliding-work-sharing/releases/tag/v0.1.0. 

When running the Default application scenario configuration using the following command, it should run the default application configuration "logistics." However, when trying to run this, it throws an error message: "Fuzzy Inference System (FIS) bean is not correctly created."

```
java -jar sliding-work-sharing-0.1.0.jar
```

### PR DESCRIPTION
**Pull request by umeshsarkar**
closes #39 

In the previuos version the `return parseFclFile(externalFuzzyRuleFile.getPath());
` and `return parseFclFile(internalFuzzyRuleResourceUrl.getPath());` in the `FuzzyInferenceSystemInitializer ` class assumes the FCL file accessible via file system path, which does not work inside a JAR. 

Using `InputStream` helped to read the contents of a file (path) and the resources inside a JAR.

### CODE REVIEW

File: src/main/java/eu/ai4work/sws/config/FuzzyInferenceSystemInitializer.java [hunk 1]
```diff
@@ -34,22 +35,22 @@ public FIS initializeFuzzyInferenceSystem() throws FileNotFoundException, Invali
...
+            return parseFclFile(internalFuzzyRuleResourceFile, fclRulesFilePath);
         }
 
         throw new FileNotFoundException("Fuzzy Control Language (FCL) file not found: " + fclRulesFilePath);
     }
 
-    private static FIS parseFclFile(String fclRulesFilePath) {
+    private static FIS parseFclFile(InputStream inputStream, String fclRulesFilePath) {
         try {
             logger.debug("Initializing a Fuzzy Inference System (FIS) based on the FCL file: " + fclRulesFilePath);
```
Comment (gr-hovest-atb) [inline src/main/java/eu/ai4work/sws/config/FuzzyInferenceSystemInitializer.java:52]: Just a minor suggestion to simplify the code: if we move this line to line 33, then we do not need to pass the `String fclRulesFilePath` parameter to this method (as it is only used for logging, not for the actual functionality).

We could also set the log level to "info" here, so that we will always see in the log which file it was trying to parse in case parsing fails (then we can also remove the `fclRulesFilePath` in the exception message in line 55).

**Review by gr-hovest-atb — APPROVED** [review]
Just a minor suggestion to simplify the code. Feel free to accept or reject it.
